### ISSUE TITLE
[rule request]: `no-empty-module-metadata`

### ISSUE THREAD

**Issue by nmatushevskiy** [angular-eslint/angular-eslint#100]
Hello!
In the process of review pull requests in my team we are very often pay attention to empty module metadata (such as "imports" or "providers" from the examples below):
```
@NgModule({
   imports: [],
   declarations: [SomeComponent],
   exports: [SomeComponent]
})
```
or 
```
TestBed.configureTestingModule({
   declarations: [TestComponent],
   providers: []
})
```

I created plugin which checks empty module metadata for ngModule and TestBed.configureTestingModule  and throws an error, if module metadata empty. 
Plugin contains two rules: for ngModule and for TestBed.configureTestingModule. Also there is an opportunity to add fields to ignore list if for some reason they not needed to be checked.

Вut it doesn’t look like a project-specific thing. Most likely, in many projects reviewers focus on empty (unnecessary) fields as on stylistic Issue. Considering that the project uses angular-eslint, I decided to propose the idea of such rules. 

If you are interested, I can open pull request.

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by JamesHenry** [comment]
Thanks again for the write up @nmatushevskiy, I think in this case it probably is most appropriate as a custom rule outside of the core plugin that this project provides. There aren't any fundamental issues caused by the code in question, and so I think it is more of a stylistic choice.

Having said that I am happy to reconsider this position if it turns out that a proportion of the community would benefit from having it in the core plugin - we haven't yet established a governance process around this so would just be an informal discussion with the other maintainers at this stage.

Cheers!
