### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by mgechev** [angular-eslint/angular-eslint#111]
This is going to be the future of [codelyzer](https://github.com/mgechev/codelyzer).

Feel free to post logo suggestions here. It'll be great if we can make it recognizable - something similar, but perhaps more modern than the official codelyzer logo:

![Logo](https://raw.githubusercontent.com/mgechev/codelyzer/master/assets/logo.png)

**Comment by beeman** [comment]
Implementation of [this comment](https://twitter.com/Bitcollage/status/1287044790232715265) by @SerkanSipahi.

![angular-eslint](https://user-images.githubusercontent.com/36491/88460452-f07b8d80-ce61-11ea-9855-320088c56bcc.png)

**Comment by beeman** [comment]
Variation on the above, an implementation of [this comment](https://twitter.com/Bitcollage/status/1287044790232715265) by @SerkanSipahi.

![angular-eslint-2](https://user-images.githubusercontent.com/36491/88460511-59fb9c00-ce62-11ea-91d4-847d349393ca.png)

**Comment by ThomasMaitret** [comment]
![Group (1)](https://user-images.githubusercontent.com/20746707/88460625-cb0c7500-ce9d-11ea-81e3-609032a12f66.png)

**Comment by ThomasMaitret** [comment]
![Group 4](https://user-images.githubusercontent.com/20746707/88461013-c5fcf500-cea0-11ea-8667-9694c707bda7.png)

**Comment by ThomasMaitret** [comment]
And the variant with inverted colours


![Group 5](https://user-images.githubusercontent.com/20746707/88461046-f3e23980-cea0-11ea-898e-4ce4728f64e6.png)

**Comment by JamesHenry** [comment]
Thanks a lot for the inspiration here guys!

I personally like having the Angular red in there - I think the overall shape does a good enough job of speaking to the ESLint connection and having the red instead of the purple also helps evoke some of the original codelyzer logo.

Having said that, I am happy to go with what the community feels strongly about!

@mgechev let me know your thoughts, maybe you could use your large twitter reach to formalize it into a poll once we feel we have a good selection? (and maybe that's already the case)

**Comment by beeman** [comment]
Changed [this logo](https://github.com/angular-eslint/angular-eslint/issues/111#issuecomment-663868419) to red.
 
![image](https://user-images.githubusercontent.com/36491/90264845-53d05e00-de17-11ea-9334-aec75c380215.png)

**Comment by beeman** [comment]
A variation (light on the back, dark on the front).

![image](https://user-images.githubusercontent.com/36491/90264958-867a5680-de17-11ea-8324-7919c8c14375.png)

Personally I don't think this conveys the message as well. Mainly because I don't really recognize the eslint part when it's not purple.

**Comment by mgechev** [comment]
I love all of them. Hard for me to choose :)

I guess I'm leaning towards [this one](https://github.com/angular-eslint/angular-eslint/issues/111#issuecomment-674125600) because it's more consistent with the Angular branding.

@wKoza, @rafaelss95 what do you think?

**Comment by wKoza** [comment]
I am a bad graphic designer, so I will not draw it :), but I would have seen the ESLINT logo with a magnifying glass in the center (or the 'A' of Angular).

![image](https://user-images.githubusercontent.com/11403260/90307645-855d2e00-ded8-11ea-9891-630598275ebb.png)

**Comment by rafaelss95** [comment]
I really like that last one from @beeman 🚀

**Comment by muuvmuuv** [comment]
Here is my version. I adjusted yours a little bit @beeman and used the original inverted logo and colors from the [press kit](https://angular.io/presskit).

Everyone can add their own version here (but please do not remove or edit someone elses): https://www.figma.com/file/m6g3nIhQvSHtJEkv3cUYti/angular-eslint-logo?node-id=2%3A87

![v1](https://user-images.githubusercontent.com/11534760/91445531-872ed600-e876-11ea-9823-f03787022564.png)

**Comment by JamesHenry** [comment]
It's very close but I think I prefer @muuvmuuv latest one - instinctively this feels like slightly more of an Angular project than an ESLint project (because of the use of schematics, builders etc), so having the red helps echo that.

@muuvmuuv are you happy if we close this and start using the image directly above?

**Comment by JamesHenry** [comment]
Thank you to everyone for their work and inspiration! ❤️

**Comment by muuvmuuv** [comment]
@JamesHenry sure, just use the Figma workspace and export it from there. Or tell me what resolution/extension you need :) glad you like it.

**Comment by JamesHenry** [comment]
Thanks @muuvmuuv 

I have applied the logo to the organization and the README, thanks again everyone!

**Comment by JamesHenry** [comment]
@muuvmuuv sorry to tag you in such an old issue but do you happen to have an SVG copy of the logo? The figma link seems to be invalid.

Separately, are you up for the challenge of bringing the logo up to date with the latest Angular branding? :)

**Comment by muuvmuuv** [comment]
Nope, the link is dead, had some re-org in my Figma Org. But started upgrading the logo, will share soon :)

**Comment by muuvmuuv** [comment]
Anyone here with an Illustrator license that can export the gradient here https://drive.google.com/drive/folders/1ox4RsIGQY7EeSRvNRWScVP_hemgZTYlq "icon_angular_gradient.qi" as 512x512 for me? Seems no application supports these kind of multi-gradients besides Adobe software. SVG would be welcome, but idk if it can be exported as such, any other high-res format will also work.

**Comment by JamesHenry** [comment]
Thank you @muuvmuuv!

**Comment by muuvmuuv** [comment]
Here we go: https://www.figma.com/design/9FHC493hzLdIyxy4EpG098/External-Stuff?node-id=0-1&t=T3Y3Dsuhb6BpQOVS-1 (but made it read-only this time). Since I was unable to mask the gradient SVG (exported from AI), it is just a PNG masked.

![Angular ESLint Logo v2](https://github.com/user-attachments/assets/82ebb2eb-72a8-4028-abfc-2df1f1ba2760)
![Angular ESLint Logo v2@2x](https://github.com/user-attachments/assets/80e939ed-9145-4e2e-888a-c3cdddbe6d0d)

**Comment by muuvmuuv** [comment]
Updated the images @JamesHenry :)

**Comment by JamesHenry** [comment]
Thank you!
