### ISSUE TITLE
"@angular-eslint/schematics" not found in collection "@schematics/angular" error on step 2

### ISSUE THREAD

**Issue by alexanderLanars** [angular-eslint/angular-eslint#131]
I got this error on the step 2 when I try to call `ng g @angular-eslint/schematics` command:

`An unhandled exception occurred: Schematic "@angular-eslint/schematics" not found in collection "@schematics/angular".`

**Comment by JamesHenry** [comment]
What are you actually running (the full command)?

Step 2 shows the command you need to run, but what you have included here is not the same as that.

**Comment by alexanderLanars** [comment]
I am running `ng g @angular-eslint/schematics:add-config-to-project {{my_prject_name}}` on several diffetent projects and got the errors like above. But after some attempts it worked.

**Comment by JamesHenry** [comment]
You would get the error above if you missed out the `:add-config-to-project` part of the command.

This is because the first part `@angular-eslint/schematics` is a namespace for the schematic collection that the generate command `g` is going to look up, and then the `:add-config-to-project` tells it which specific schematic to lookup within that collection.

If you run just `g @angular-eslint/schematics` it will try and look up a _schematic_ called `@angular-eslint/schematics` within the default collection. The default collection is the one the Angular CLI provides out of the box which is `@schematics/angular`.

Hopefully that helps clarify all the moving parts!

**Comment by alexanderLanars** [comment]
I was doing all like this. But thank you anyway :)

**Comment by hanct** [comment]
> You would get the error above if you missed out the `:add-config-to-project` part of the command.
> 
> This is because the first part `@angular-eslint/schematics` is a namespace for the schematic collection that the generate command `g` is going to look up, and then the `:add-config-to-project` tells it which specific schematic to lookup within that collection.
> 
> If you run just `g @angular-eslint/schematics` it will try and look up a _schematic_ called `@angular-eslint/schematics` within the default collection. The default collection is the one the Angular CLI provides out of the box which is `@schematics/angular`.
> 
> Hopefully that helps clarify all the moving parts!

Hi, 

is the {{my_project_name}} suppose to be the name of the folder that contain the angular.json?  Is {{ and }} suppose to be part of the command?  I ask this cos i encounter same error message.
