### ISSUE TITLE
[interpolation-space] Rule request to add or remove space in interpolations

### ISSUE THREAD

**Issue by muuvmuuv** [angular-eslint/angular-eslint#1315]
I would like to enforce all in our codebase to add spaces around the variable in an interpolation.

```HTML
{{varName}}
```

→ 

```HTML
{{ varName }}
```

With a little help, I would contribute it.

**Comment by JamesHenry** [comment]
Hi @muuvmuuv, please check out https://github.com/angular-eslint/angular-eslint/blob/main/docs/FORMATTING_RULES.md

I don't want to repeat that doc too much but essentially this is something you would need to build yourself outside of this project, although you can freely benefit from the `@angular-eslint/utils` package when doing so. As per those notes, though, I personally would highly recommend using prettier for this purpose instead of ESLint.

**Comment by muuvmuuv** [comment]
Sry, hard to find that by searching. I cannot think of a time when prettier does that kind of formatting, any links? Thought as this is very Angular specific that it fit well, but will implement it by my own.

**Comment by JamesHenry** [comment]
@muuvmuuv There is already a link to that doc in a dedicated section on the README: https://github.com/angular-eslint/angular-eslint/tree/9ecf4acc786d8529c6110db8842303286df80103#philosophy-on-lint-rules-which-enforce-code-formatting-concerns

Here is the prettier behaviour in action:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuExgDcCGAnAcpgWzgF9iQAaECABxgEtoBnZUHbCAdwAUcFmVMAGw6YAns0oAjbJjABrODADKhOABk6UOMgBmQxnCkz5ipdVmaA5shjYAroZBwCkuABM37tZiiW7mSzgAMQhsAkwYel9kEEw7GAgKEAALGAJBAHVkunhGczA4JT4cunQc0RiwRgkQTQNsGC4ZS3DdfUcAK0YADyUrQTgARTsIeDbBA0pzbHqYnz9BHCTqbE0YDLo3GGTkAA4ABin2AwyZahiVuHr0bUoARxH4Jpp+WMYAWi13dyTsOAe6H8mgFWkg9BNHAYCHQbPZIf0ho9tGD2pQYJhJBstjskAAmNEyOiCKwAYQgBFBTkYAFYknYDAAVDH8cGTEDoBwASSgnlgSjAq1oAEEeUoYKIBuMDKQgA

Before prettier on the left, after prettier on the right. Prettier has had a dedicated angular parser to support templates for a couple of years now.

**Comment by muuvmuuv** [comment]
👍 totally understandable. Just noticed that my auto formatting was set on a different formatter than prettier so I never saw that functionallity... should have checked that before
