### ISSUE TITLE
constructor error

### ISSUE THREAD

**Issue by miku3920** [angular-eslint/angular-eslint#132]
```
export class MyFormModel {
	constructor(				// Useless constructor.eslint(no-useless-constructor)
		public msg: string		// 'msg' is defined but never used.eslint(no-unused-vars)
	) { }						// Unexpected empty constructor.eslint(no-empty-function)
}
```
Here's my updated `.eslintrc` file
```
extends: ['plugin:@angular-eslint/recommended', 'plugin:@typescript-eslint/recommended'],
rules: {
    'no-useless-constructor': 'off',
    'no-empty-function': 'off',
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars': 'error',
```

**Comment by JamesHenry** [comment]
Thanks @miku3920, right now I don't think this is quite a reproduction of the issue, because `this.msg` isn't used anywhere.

Are you using the latest typescript-eslint (v4)? The scope analysis has been completely redone and so rules like no-unused-vars should be more accurate now.

I would suggest that you update the integration-tests in this repo to reproduce your issue and then link to your fork with the minimal changes needed. Then I'm definitely happy for you to reopen this for it to be investigated.

Many thanks!
