### ISSUE TITLE
Cross-platform dev npm scripts

### ISSUE THREAD

**Issue by AlexanderFSP** [angular-eslint/angular-eslint#141]
There is an issue with dev npm scripts for now, that they work pretty in UNIX-like systems, but on Windows to build packages (in this case `@angular-eslint/builder`) I had to rewrite scripts and installed needed dependencies to test & contribute:

```
"build": "rm -rf ./dist && tsc --project tsconfig.build.json && terser ./dist/index.js --output=./dist/index.js",
"postbuild": "cp src/schema.json dist/"
```

```
"build": "rimraf ./dist && tsc --project tsconfig.build.json && terser ./dist/index.js --output=./dist/index.js",
"postbuild": "copy src\\schema.json dist\\"
```

**Comment by MikeMatusz** [comment]
Thanks @AlexanderFSP! I was also just trying to work with this repo on Windows, and these changes would definitely help.  I'm not sure they'll be quite enough on their own, though, as integration tests will still fail due to backslashes in the `FIXTURES_DIR` path.

Specifically, in [normalizeOutput](https://github.com/angular-eslint/angular-eslint/blob/a60ae990df38c6506e96ff03399dbbaeb3866d8d/packages/integration-tests/tests/integration.ts#L7) it calls `new RegExp(FIXTURES_DIR, 'g')` and errors out because of the un-escaped terminal backslash.  Locally, I worked around it using a `.replace(/\\/g, '\\\\')` and then also had to replace the '\\\\' on the way out with '/', though it might be better accomplished using a custom serializer as described [here](https://kentcdodds.com/blog/effective-snapshot-testing).

**Comment by MikeMatusz** [comment]
Attempted the custom serializer locally, and it's a little too aggressive, also clearing some intentional escape characters in the output.  Could probably get it working, but I think just changing `normalizeOutput` to the following might be simplest:
```ts
return value.replace(new RegExp(`^${FIXTURES_DIR.replace(/\\/g, '\\\\')}(.*?)$`, 'gm'), (_, c1) => `__ROOT__/${c1.replace(/\\/g, '/')}`);
```
I can create a separate issue if preferred, but since you need to be able to run integration tests, and potentially update snapshots, to contribute, it seems related.

**Comment by AlexanderFSP** [comment]
Hi, @MikeMatusz . Yeah, I'll try to fix it. Thanks for your response!
