### ISSUE TITLE
Python 3 and Desktop development with C++ of Visual Studio are required after updating to Angular 16 

### ISSUE THREAD

**Issue by peter-wong-d** [angular-eslint/angular-eslint#1560]
**Python 3 and Desktop development with C++ of Visual Studio are required after updating to Angular 16 **

I had an angular project which was running  @angular/cli 15.2.4" with @angular-eslint/builder 15.2.4.

In order to build or run lint after the update, Python 3 and Desktop development with C++ of Visual Studio must be installed. What is the reason for?

Thank you very much.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `16.2.0` |
| `ESLint`                           | `8.28.0` |
| `node`                             | `16.20.2` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 16.2.5
Node: 16.20.2
Package Manager: npm 8.19.4
OS: win32 x64

Angular: 16.2.8
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.5
@angular-devkit/build-angular   16.2.5
@angular-devkit/core            16.2.5
@angular-devkit/schematics      16.2.5
@angular/cdk                    16.2.7
@angular/cli                    16.2.5
@schematics/angular             16.2.5
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3

```

- [ x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by abaran30** [comment]
Hi @peter-wong-d. This looks like an issue of getting Angular 16 running on your machine, rather than an issue with the angular-eslint package itself. I would recommend the following:
1. Consider using a more recent version of Node (current LTS is 20.9.0) and npm
2. Troubleshoot getting [Angular (as a platform)](https://github.com/angular/angular) v16 running on your machine

I will close this issue. Should you get to a point where Angular 16 is running but you're having issues with angular-eslint (meaning that ESLint and other ESLint plugins work, but angular-eslint does not), please open a new issue.
