### ISSUE TITLE
[prefer-control-flow] can we have a option to ban the new control flow?

### ISSUE THREAD

**Issue by Jordan-Hall** [angular-eslint/angular-eslint#1645]
**Description and reproduction of the issue**

Currently prefer-control-flow only has a true and false. However there appears to be no rule to ban the use of the new control flow syntax because sorry its 😷 and its showing in my age 😂. Would you be willing to extend this with the option to ban control flow ?

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.5
@angular-devkit/build-angular   16.2.5
@angular-devkit/core            16.2.5
@angular-devkit/schematics      16.2.5
@angular/cdk                    16.2.7
@angular/cli                    16.2.5
@angular/fire                   7.6.1
@angular/language-service       16.2.10
@angular/material               16.2.7
@schematics/angular             16.2.5
ng-packagr                      16.2.3
rxjs                            7.8.1
typescript                      4.9.5
zone.js                         0.13.1

**Comment by json-derulo** [comment]
Other than personal preference, what do you think are the benefits of continuing to use the directives instead of the control flow? There are really good arguments for the control flow. The loops are up to 90% faster in runtime. There are more features, like else-if. Also type narrowing works better. I don't see any good reason why one should not prefer the control flow. Read more in the [Angular 17 blog post](https://blog.angular.io/introducing-angular-v17-4d7033312e4b).

Also I don't think it makes sense to have a rule `prefer-control-flow` with an option to do the exact opposite. If this feature is offered, I think it should be a separate rule.

**Comment by Jordan-Hall** [comment]
Agree name may not be best but I think it should be linked hence using it.

Directives are more flexible, it's more standard for HTML too. Alot of the apps I use tend to learn towards zoneless anyway.  The 90% better speed is also not exactly true, async and if was never really optimized for speed.

**Comment by JamesHenry** [comment]
@Jordan-Hall I don't feel like it makes sense to have a rule in angular-eslint itself which directly goes against the clear direction of the framework (regardless of what the opinions on that direction are). In the same way we don't have a an option on `prefer-standalone-components` which prefers the usage of non-standalone components.

Everyone is entitled to their own preferences and we provide the `@angular-eslint/utils` package so that you more easily write your own custom rules, but yeah this wouldn't be a good fit for the main plugin
