### ISSUE TITLE
Rule proposal: Add check for restriction on hyphens in pipe names

### ISSUE THREAD

**Issue by mgechev** [angular-eslint/angular-eslint#17]
Author @jbogarthyde in https://github.com/mgechev/codelyzer/issues/879.

Giving a pipe a name with hyphens causes a compilation error. A contributor suggested adding a check to codelyzer.

https://github.com/angular/angular/issues/31787

**Comment by rafaelss95** [comment]
Hey @mgechev I remember that we've removed the _pipe-naming_ rule from Codelyzer some time ago. Do you think that it worth bringing it back here? I remember that you've mentioned here https://github.com/mgechev/codelyzer/issues/519#issuecomment-366785640 that it was being deprecated because a kebab-cased selector causes a compile-time error. Anyway, let me know your opinion about this and I could see how I could help :)

**Comment by mgechev** [comment]
Yes, that's right. We can close the issue since the error is still at compile-time with Ivy.
