### ISSUE TITLE
Recommended config uses external rules

### ISSUE THREAD

**Issue by jsaguet** [angular-eslint/angular-eslint#178]
I've noticed that [recommended config](https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin/src/configs/recommended.json) from the eslint plugin declares rules that are external to the plugin.
For example it uses these plugins:
```json
"plugins": [
    "eslint-plugin-import",
    "eslint-plugin-jsdoc",
    "eslint-plugin-prefer-arrow"
],
```
and declares a few rules from packages like `eslint`, `@typescript-eslint`

Doing this has a number of drawbacks:
- it forces the users to npm install other dependencies like eslint-plugin-jsdoc or eslint-plugin-imports which they may not need or want
- it adds rules configuration that the users now have to manually reconfigure to match what they are expecting
- it is complicated for users to identify where the rule configuration is coming from since they will most likely look into the related plugin's recommended config instead of this one

In my opinion, recommended config should only give recommended configuration for rules inside this plugin.

Is there any particular reason why recommended config uses external rules that I'm not seeing ?

**Comment by JamesHenry** [comment]
The reason for the config being the way it is is very simple - it is what is required to match the current tslint.json that the Angular CLI ships with today (yes, including the extra plugins).

When using the Angular CLI the point around installation is also moot because the ng-add schematic handles that all for the user automatically.

However, it does raise the point that we should look to differentiate between the Angular CLI use-case (I imagine the common case by some distance) and the custom use-case. People should still have an easy to use config specific to these plugins even if they are hand-crafting their setup for whatever reason.

**Comment by JamesHenry** [comment]
Plus we can then differentiate between "how things used to be done" and "how things _should_ be done" more easily.

I will implement some additional configs to address this 👍

**Comment by jsaguet** [comment]
What I understand is that the current recommended config is actually a default eslint config that should be created when user migrates from tslint or when a new project is created with ng cli and eslint (whenever it will be possible). 
So, shouldn't that file be generated by a schematic instead of using the recommended config of this package to enforce the config?

This way it would be much easier for users to adapt what they want since this is the current behavior when we create a new project with CLI and Tslint

Having multiple configurations could be really useful indeed, especially the differentiation between iso-configuration from codelyzer and what opinionated view this plugin promotes.

Really looking forward to the specific angular-eslint recommended config 👍

**Comment by JamesHenry** [comment]
> This way it would be much easier for users to adapt what they want.

IMO this is touching on the classic friction in tool development, specifically configuration for tool:

Concise and declarative vs verbose and imperative (user "controls" everything)

They both have pros and cons which is why there is little consensus to be found in the development community.

ESLint configs, in order to support Angular as an advanced use-case, are baseline much more scary looking than TSLint. ESLint does not understand TypeScript or HTML out of the box, then you factor in extracting inline templates and treating them as if they were HTML...

Therefore it is my view that abstracting the default configuration is helpful in removing some of the rarely changed aspects of the boilerplate to make the overall config easier to grok. The user still has full control over disabling rules and plugins used in their configs.

**Comment by JamesHenry** [comment]
I would also note that the Angular CLI also extends from an additional config out of the box, it does not inline the contents

**Comment by guilhermetod** [comment]
Hey @JamesHenry I just updated my package and realized there are some peer dependency error because of these additional configs. Since I'm not using the cli-compat version, I didn't install these packages.

This isn't much of a big deal since it's only a warning on install and on npm ls, but I think it's worth mentioning this in case you want to change it. [This has been a problem here too](iamturns/eslint-config-airbnb-typescript#6) and maybe a change earlier would be easier to make rather than when the package is more widely adopted or officialy shipped with Angular.
