### ISSUE TITLE
Error: '@angular-eslint/template-parser'

### ISSUE THREAD

**Issue by DmitriyTanase** [angular-eslint/angular-eslint#180]
- [ + ] I have tried restarting my IDE and the issue persists.
- [ - ] I have updated to the latest version of the packages.
- [ + ] I have [read the FAQ](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md) and my problem is not listed.

**eslintrc.js**

```eslintrc.js
module.exports = {
  parser: "@angular-eslint/template-parser",
  parserOptions: {
    project: './tsconfig.json',
    sourceType: "module"
  },
  env: {
    "browser": true,
    "es6": true,
    "node": true
  },
  ignorePatterns: ["node_modules/**/*", "**/node_modules/**/*", "dist/**/*"],
  extends: [
    'eslint:recommended',
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    'plugin:@angular-eslint/recommended',
    "prettier",
    "prettier/@typescript-eslint"
  ],
  plugins: [
    "eslint-plugin-import",
    "@angular-eslint/eslint-plugin",
    "eslint-plugin-jsdoc",
    "@angular-eslint/eslint-plugin-template",
    "eslint-plugin-prefer-arrow",
    "@typescript-eslint",
    "@angular-eslint",
    "prettier",
    'simple-import-sort',
    // "@typescript-eslint/tslint"
  ],
  rules: {
...
"@angular-eslint/no-conflicting-lifecycle": "error",
    "@angular-eslint/no-host-metadata-property": "error",
    "@angular-eslint/no-input-rename": "error",
    "@angular-eslint/no-inputs-metadata-property": "error",
    "@angular-eslint/no-output-native": "error",
    "@angular-eslint/no-output-on-prefix": "error",
    "@angular-eslint/no-output-rename": "error",
    "@angular-eslint/no-outputs-metadata-property": "error",
    // "@angular-eslint/template/banana-in-box": "error",
    "@angular-eslint/template/no-negated-async": "error",
    "@angular-eslint/use-lifecycle-interface": "error",
    "@angular-eslint/use-pipe-transform-interface": "error",
    "@typescript-eslint/adjacent-overload-signatures": "error",
    "@typescript-eslint/array-type": "off",
...
}
```
**tsconfig.json**
```TS
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "module": "es2020",
    "lib": [
      "es2018",
      "dom"
    ],
    "include": [
      "src",
      "eslintrc.js",
      ".eslintrc.js"
    ]
  }
}

```

**Expected Result**
In progress migration an angular app from tslint to eslint
Successful linting with eslint

**Actual Result**
```
 eslint "./src/**/*.ts"


Oops! Something went wrong! :(

ESLint: 7.13.0

Error: Error while loading rule '@angular-eslint/template/banana-in-box': You he 'parser' in your ESLint config.
Occurred while linting D:\Projects\VTB\WebClient\src\app\animations.ts
    at Linter._verifyWithConfigArray (D:\Projects\VTB\WebClient\node_modules\eslint\lib\linter\linter.js:1271:21)
    at Linter.verify (D:\Projects\VTB\WebClient\node_modules\eslint\lib\linter\linter.js:1226:25)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! web-client@0.0.0 eslint: `eslint "./src/**/*.ts"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the web-client@0.0.0 eslint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hi-tech\AppData\Roaming\npm-cache\_logs\2020-11-13T13_39_40_039Z-debug.log
```

**Additional Info**
At first I replace parser as tolds me error, error from 'problems' tab in VS go out, but in console I get that error again
At second I commented out line of code whitch contains banana-in-box, as you can see, but its didnt help
Help me resolve this

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint/eslint-plugin` | "4.3.0" |
| `@typescript-eslint/parser`        | "^4.7.0" |
| `TypeScript`                       | "^4.0.5" |
| `ESLint`                           | "^7.6.0" |
| `node`                             | "12.18.4' |

**Comment by JamesHenry** [comment]
Hi @DmitriyTanase, please take a look at this section of the README where it outlines how it is critical that we separate template and source code concerns using overrides: https://github.com/angular-eslint/angular-eslint#notes-on-eslint-configuration.

We cannot set a single parser at the top level of the config and expect things to work, we need one parser for HTML files, one parser for TS files and they have no overlap.

That section in the README also links off the integration tests within this project which show how overrides can be used, as well as to the ESLint documentation which obviously explains them at a conceptual level as well.

Currently in your config above you have all the HTML and TS concerns mixed in together and so that is the reason for the issues.

For Angular + ESLint, the root level of the config is basically unusable for us - we need to put everything in a nested config block in overrides for maximum predictability and separation of concerns.

Hope that helps!

**Comment by DmitriyTanase** [comment]
thx @JamesHenry  for quickly answer, yes its been helpful! In every section of "overrides" I must use different parsers? For *.ts and *.html files? like that:
```
module.exports = {
  root: true,
  overrides: [
    {
      files: ["*.ts"],
      parser: "@angular-eslint/parser",
      parserOptions: {
        project: [
          "tsconfig.json"
        ],
        createDefaultProgram: true // What do default program?
      },
      extends: [
        "plugin:@angular-eslint/ng-cli-compat", // what do ng-cli-compat? Formatting code instead prettier?
         "plugin:@angular-eslint/template/process-inline-templates"
      ],
      rules: {
        "@angular-eslint/directive-selector": [
          "error",
          { "type": "attribute", "prefix": "app", "style": "camelCase" }
        ],
        "@angular-eslint/component-selector": [
          "error",
          { "type": "element", "prefix": "app", "style": "kebab-case" }
        ]
      }
    },
    {
      files: ["*.html"],
      parser: "@angular-eslint/template-parser",
      parserOptions: {
            project: [
              "tsconfig.json"
            ],
      extends: ["plugin:@angular-eslint/template/recommended"],
      rules: {
        "max-len": ["error", { "code": 140 }]
      }
    }
  ]
}
```

**Comment by JamesHenry** [comment]
Thanks @DmitriyTanase this is useful and will help us make the documentation better.

Here are some notes on your snippet above (which I will try and incorporate into the docs):

- There is no such thing as `@angular-eslint/parser` - for your TS files it should be the standard `@typescript-eslint/parser`
- `createDefaultProgram` is a fallback we have to use for Angular projects because it contains some files that are not technically included in the TypeScript programs that get created behind the scenes for your project (mainly `environment.prod.ts`). The Angular Team is working to address this.
- `ng-cli-compat` is just a shareable ESLint config which saves the end user from having to figure out an ESLint config which matches up with the current TSLint config which the Angular CLI creates today
- You do not need `parserOptions` for your .html config block, because `@angular-eslint/template-parser` does not currently have any `parserOptions`, so you should just remove that
- I am personally not a fan of using a linter to enforce formatting concerns so I would not use `"max-len": ["error", { "code": 140 }]` for your templates and instead use a dedicated code formatter like Prettier. However, that is my subjective opinion and there is nothing functionally wrong with that rule config

**Comment by DmitriyTanase** [comment]
Agreement with u, that rule only for testing what `@angular-eslint/template-parser` currently working, a lot of thanks for your help!  
- Now it works fine 
- Tell me pls where are placing `ng-cli-compare`? He is got me trouble(`not found`). In directory `node_modules/@angular-eslint/eslint-plugin` doesnt seen his.
- Anyway linting is working and I will try add AirBnB.

**Comment by JamesHenry** [comment]
Make sure you are on the latest version, the ng-cli-compat was only added recently.

Also you have written compare above rather than compat, so that would also be an issue if you did that in your config.

compat is just short for compatibility
