### ISSUE TITLE
Updated to Angular 11. Getting Error: Angular CLI v10.1.0 and later (and no `tsconfig.base.json`) is required in order to run this schematic. 

### ISSUE THREAD

**Issue by windcloak** [angular-eslint/angular-eslint#195]
I updated my project to Angular 11.

I ran this and got the following error. It did not install anything. How do I fix this?
```
ng add @angular-eslint/schematics

Error: Angular CLI v10.1.0 and later (and no `tsconfig.base.json`) is required in order to run this schematic. Please update your workspace and try again.
```

**Comment by JamesHenry** [comment]
Hi @windcloak, this suggests that you may have manually updated your Angular workspace at some point in the past (instead of using the automatic process provided by ‘ng update’)

Angular briefly used the tsconfig.base.json but switched away from it again, back to a tsconfig.json at the root.

ng update would have handled this change for you automatically.

Maybe you could go back and redo your update using ng update?

**Comment by windcloak** [comment]
I got it working, but I had to delete `tsconfig.base.json` before running 
`ng add @angular-eslint/schematics`
and
`ng g @angular-eslint/schematics:convert-tslint-to-eslint {{YOUR_PROJECT_NAME_GOES_HERE}}`

I had to restore `tsconfig.base.json` before running the last line,
`npx ng lint {{YOUR_PROJECT_NAME_GOES_HERE}}`

**Comment by JamesHenry** [comment]
@windcloak You haven't acknowledged anything I said and so **your solution is not appropriate**.

I am adding some more information about you and others ended up with this issue here: https://github.com/angular-eslint/angular-eslint/pull/203/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R28

**Comment by LeoLfL** [comment]
hi. i had the same issued after I updated angular to the 11 version using `--force` params. I fixed it using this 
```
ng update @angular/cli --migrate-only --from 9 --to 11
ng update @angular/core --migrate-only --from 9 --to 11
```

**Comment by jakehockey10** [comment]
@LeoLfL exactly what I needed.  Thanks!

**Comment by itayperry** [comment]
I've just started a new project with Angular 11 and `tsconfig.base.json` exists.. I don't understand. Are you sure @JamesHenry that it shouldn't be there?

![image](https://user-images.githubusercontent.com/37377389/116817247-0c892980-ab6e-11eb-8900-d025d1c75818.png)

**Comment by davija** [comment]
Ok, kind of ironic... You say they migrated to `tsconfig.base.json` and then migrated back at a later point.  However, in this very project you  have a `tsconfig.base.json`...
