### ISSUE TITLE
[bug] relative-url-prefix logs error on ../ prefix

### ISSUE THREAD

**Issue by bgotink** [angular-eslint/angular-eslint#200]
The `relative-url-prefix` rule logs an error on `../` prefix for `templateUrl`/`styleUrls`. It also complains for `./../`.

**Comment by JamesHenry** [comment]
Looks like this functionally is currently at parity with Codelyzer and someone opened an issue there: https://github.com/mgechev/codelyzer/issues/816

@mgechev @wKoza @rafaelss95 what is the correct resolution to this across both tools?

**Comment by wKoza** [comment]
Hi,
It seems to be a bug. We only need to have a relative url. Whatever we do after that.

**Comment by rafaelss95** [comment]
It's interesting because we have some tests that explicitly disallow the cases described by @bgotink and in mgechev/codelyzer#816...

this:

https://github.com/angular-eslint/angular-eslint/blob/e3a5796f28b20a6b6e64ba752f5a2d351b778109/packages/eslint-plugin/tests/rules/relative-url-prefix.test.ts#L57

and this:

https://github.com/angular-eslint/angular-eslint/blob/e3a5796f28b20a6b6e64ba752f5a2d351b778109/packages/eslint-plugin/tests/rules/relative-url-prefix.test.ts#L90

<hr>

Do you guys think that we should rework this rule (it means the rule itself, docs and tests) to cover these cases or would it be the case of perhaps adding an option so that the user could enable these situations if desired? Btw, here's the [style guide link](https://angular.io/guide/styleguide#style-05-04) for this rule.

Whatever the decision, I am willing to help with that.

**Comment by wKoza** [comment]
IMO, your 2 examples are OK. We work with relative path. we should accept ` styleUrls: ['./foobar.css']`and `styleUrls: ['../foobar.css']`.  In other words, we only have to accept `./`and `../`

**Comment by JamesHenry** [comment]
Thanks guys, then I think this is definitely something we can accept PRs on to change the rule
