### ISSUE TITLE
(template-parser) loc for each children

### ISSUE THREAD

**Issue by Quramy** [angular-eslint/angular-eslint#209]
Hi @JamesHenry 

I'm confused why each children node does not have `loc` or `range`. 
 
<img width="1623" alt="スクリーンショット 2020-12-03 14 45 42" src="https://user-images.githubusercontent.com/1262998/100970525-70380800-3578-11eb-8260-980708c911da.png">

I'm trying to add `@angular-eslint/template-parser` via https://github.com/fkling/astexplorer/pull/553, but I don't understand who should calculate location object.

- (a) User(e.g. rules or ast explorer parser) of the result of the template-parser should calculate this
- (b) template-parser itself should calculate location of the all nodes.

**Comment by JamesHenry** [comment]
Hi @Quramy, the AST that the Angular compiler produces for us does not use `loc` or `range`.

We have had to apply those data points to the `Program` node in order to get ESLint to function, but so far it has not been necessary to do much more AST transformation than that (we do a very simple assignment for a `type` property on each node right now, but that is it). Naturally we want to avoid doing any work on the AST that we don't have to because that will slow down the overall linting run.

As you can see above, the AST provides it's location data via `sourceSpan`, `startSourceSpan`, `endSourceSpan`. I can't speak to why this convention was chosen, but hopefully that is useful to you within astexplorer.net

I don't think this is something we will look to change in the near future, unless it is required for some linting functionality, so marking as a `wontfix` for now.

**Comment by JamesHenry** [comment]
Arguably there could come a point where it is more optimal to do the conversion upfront and then not use `convertNodeSourceSpanToLoc` in the rules, so this is something we can keep thinking about but as I say, we have a few more pressing items right now.

If you wanted to start POCing something we could definitely take a look together
