### ISSUE TITLE
Rule proposal: no-useless-constructor

### ISSUE THREAD

**Issue by JounQin** [angular-eslint/angular-eslint#25]
Context: https://github.com/typescript-eslint/typescript-eslint/issues/1164#issuecomment-548642565

**Comment by JamesHenry** [comment]
@JounQin this is not something that the Angular CLI TSLint + Codelyzer setup provided and as such is a lower priority right now.

If you want to work on it I would be very happy to review a PR!

**Comment by rafaelss95** [comment]
@JounQin I created a stackblitz to check if it still happens on Angular 10 (Ivy) and I couldn't reproduce it.

Could you check it [**here**](https://stackblitz.com/edit/angular-ivy-j2tkzs)? Note that the "AppComponent" extends "Base" and it doesn't need a constructor to compile.

Let me know if I'm missing anything. Regards.

**Comment by JounQin** [comment]
@rafaelss95 Thanks for your reply, `@Directive()` is required in your demo, and we're using some libraries which have not been updated like this, so `super(injector)` is still required for us.

**Comment by rafaelss95** [comment]
> `@Directive()` is required in your demo

Yes, since Ivy we must use `@Directive` for "Base" classes. Refer to https://angular.io/guide/ivy-compatibility#changes-you-may-see, https://angular.io/guide/migration-undecorated-classes and https://github.com/angular/angular/pull/31650 (the PR that contains the migration to add `@Directive` automatically when you run `ng update`).

> and we're using some libraries which have not been updated like this, so `super(injector)` is still required for us.

Hmm, I'm not sure if it's within the scope of the project to create a rule that would only be needed for apps / libs that aren't upgrade to use Ivy yet, but @JamesHenry and @mgechev could have a better opinion on this.

**Comment by mgechev** [comment]
>Hmm, I'm not sure if it's within the scope of the project to create a rule that would only be needed for apps/libs that aren't upgrade to use Ivy yet, but @JamesHenry and @mgechev could have a better opinion on this.

I agree that this seems out of the scope of the project. I'd recommend disabling the rule for the affected lines until you update to Ivy.

**Comment by JounQin** [comment]
@mgechev Although we've migrated to Ivy, but `enableIvy: false` is still available in Angular 11.

**Comment by JamesHenry** [comment]
I think I'll go with the consensus of the team here that this can be disabled by the user if they are still unable to migrate to ivy for whatever reason, but that given that ivy has been the default for a few major versions now this should be an uncommon issue for most folks.

Thanks all!
