### ISSUE TITLE
options for valid aria attributes rule

### ISSUE THREAD

**Issue by FDIM** [angular-eslint/angular-eslint#271]
It would be nice if I could provide an exceptions list/ignored properties list for `@angular-eslint/template/accessibility-valid-aria` rule.

I enabled this rule and ended up with this error:
![image](https://user-images.githubusercontent.com/1985429/103348391-291b3500-4a9a-11eb-8111-7597c7eef42a.png)

In this particular case `variant` is an `@input` of a button. Ideally of course this should not be an issue, but I doubt eslint has enough information to infer this.

If someone agrees, I could open a PR :)

**Comment by rafaelss95** [comment]
It's a bug because the current selector

https://github.com/angular-eslint/angular-eslint/blob/042cb7a7d7e32ecc35d27aaeabb1f55dd7a0123b/packages/eslint-plugin-template/src/rules/accessibility-valid-aria.ts#L33

... performs a search for attributes/inputs that **contain** `aria-`, when in fact we should only search for attributes/inputs that **start** with `aria-`:

`'TextAttribute[name=/^aria-*/], BoundAttribute[name=/^aria-*/]'({ `
