### ISSUE TITLE
Supported rules of original ESLint

### ISSUE THREAD

**Issue by Eccenux** [angular-eslint/angular-eslint#286]
I think it would be nice to add some info on which rules are supported from ESLint. All of them? Some of them? Untested?

I was specifically looking for an indentation rule and this seems to work:

```json
			"rules": {
				"indent": ["error", "tab"],
				"@angular-eslint/component-selector": [
```

So maybe add some info in [angular-eslint#rules-list](https://github.com/angular-eslint/angular-eslint#rules-list.).

PS: Also note that if you put indent rule in the html then you get a weird error like:  
\> "An unhandled exception occurred: Cannot read property 'start' of undefined"  
Maybe also worth documenting?

**Comment by JamesHenry** [comment]
Hi @Eccenux in v1 we did not convert `indent` because we believe that code formatting should be handled by a dedicated code formatter, rather than a linter.

I agree that this was somewhat confusing, so in v2, we have changed that so that `indent` will be converted, but a warning will be logged which explains our view on linters vs formatters.

As for using indent on HTML, yes that makes sense as the indent rule is a generic JavaScript rule from ESLint wand has not been written to work on HTML.

Again, this is an argument for a dedicated code formatter, such as https://prettier.io, which supports HTML as a first-class use-case.
