### ISSUE TITLE
Checkstyle xml is invalid

### ISSUE THREAD

**Issue by OrangeDog** [angular-eslint/angular-eslint#289]
See https://github.com/angular/angular-cli/issues/14659

With eslint in Angular 11 the problem is even worse, as it writes an xml file to stdout for every file instead of every project.

**Comment by JamesHenry** [comment]
Hi @OrangeDog

It's more likely that community members (this project is 100% unpaid and community-driven) will volunteer to help you with your use-case if you provide a clear write up of your issue rather than linking to other projects and potentially outdated or non-applicable discussions.

Please feel free to reopen once you have chance to provide a write up for others to read through, or open a PR with a solution and we can take it forward from there.

Thanks!
