### ISSUE TITLE
error  Parsing error: '>' expected

### ISSUE THREAD

**Issue by westlakem** [angular-eslint/angular-eslint#306]
My HTML file is pretty simple.
```
<app-header></app-header>
<router-outlet></router-outlet>
<app-footer></app-footer>
```
and it's throwing this error:
```
C:\devl\js\xxxxxxxxx\src\app\app.component.html
  1:4  error  Parsing error: '>' expected
```

This is what the CLI command created for eslintrc.json
```
{
  "root": true,
  "ignorePatterns": [
    "projects/**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": [
          "tsconfig.json",
          "e2e/tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/ng-cli-compat",
        "plugin:@angular-eslint/ng-cli-compat--formatting-add-on",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "rules": {
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": "app",
            "style": "kebab-case"
          }
        ],
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "app",
            "style": "camelCase"
          }
        ]
      }
    },
    {
      "files": [
        "*.html"
      ],
      "extends": [
        "plugin:@angular-eslint/template/recommended"
      ],
      "rules": {}
    }
  ]
}
```

**Comment by rafaelss95** [comment]
Hey @westlakem, I just tested it locally and I couldn't reproduce it. Which version (Angular, eslint, angular-eslint) are you using? Would you also mind creating a clean repository to demonstrate this problem? Thanks.

**Comment by JamesHenry** [comment]
Given we haven't heard from @westlakem I am going to close this as it's currently not possible to reproduce the issue from the provided config.

@westlakem Please feel free to reopen the issue if you are available to provide a reproduction of the issue.

Many thanks! 🙏

**Comment by lespacedunmatin** [comment]
We have the same issue. 
```
"@angular/core": "~11.0.5",
"@angular/cli": "~11.0.3",
"@angular-eslint/eslint-plugin": "^0.8.0-beta.5",
"eslint": "^7.24.0"
```

**Comment by lespacedunmatin** [comment]
The issue is also referenced in https://github.com/angular-eslint/angular-eslint/issues/81.

**Comment by JamesHenry** [comment]
@lespacedunmatin Please don't comment on closed issues, it's an inefficient way to get support because it makes things really hard to track.

The README should be your go to resource, all these relevant points are documented:

- It shows that the latest version of the library is 4.2.0, however you are using a heavily outdated, prerelease version.
- It documents which version of the Angular CLI is intended to be used with each version of angular-eslint, however you are not following that guidance with the above combination.
- It explains in great detail how eslint configs need to be set up (using overrides) to ensure that the right eslint parser is parsing the appropriate files (HTML and TS require entirely different parsers).

All of these are currently issues with your setup, but the last one is the most pertinent and the reason you are seeing this particular error message.

If you are still having trouble, once you have read through the README, and have updated your project to follow the guidelines it outlines as best you can, please feel free to open a new issue and follow the template and I would be delighted to help you resolve any remaining problems.
