### ISSUE TITLE
directive-class-suffix rule not compatibly with Ivy requirements

### ISSUE THREAD

**Issue by rootix** [angular-eslint/angular-eslint#353]
Since Angular 9 and Ivy, undecorated abstract base classes which use Angular features have to be decorated with an empty `@Directive` (or `@Component` without template, but this seems to cause runtime issues at least in Angular 9). In many cases, those abstract classes are not really a Directive or Component and may therefore not have this Suffix. 

The examples provided by Angular would cause this rule to trigger: https://angular.io/guide/ivy-compatibility-examples#undecorated-classes

Shouldn't abstract classes be excluded from this rule?

**Comment by JamesHenry** [comment]
Based on this, I think it only really applies to "selectorless" Directives

E.g. from those docs:

```ts
@Directive()            // selectorless, so it's not usable directly
```

So I think rather than looking at the class, we could have the rule take into account whether or not the Directive has been configured with a selector and not raise a lint error in that case... 🤔 

I'm really on the fence about this one, sometimes using `// eslint-disable-next-line` is the better course of action rather than adding exceptions into lint rules, and maybe this is one of those time...

Paging @mgechev @rafaelss95 for a consult 😄

**Comment by mgechev** [comment]
Explicitly disabling the rule as @JamesHenry suggested makes sense.

I like the idea of checking if `@Directive` is empty. An additional check could be verifying if it's decorating an abstract class.

I don't think the latter is a requirement of the compiler, but seems semantically accurate.

**Comment by rafaelss95** [comment]
+1 for checking "selectorless" Directives.
