### ISSUE TITLE
@angular-eslint/builder upgrade request

### ISSUE THREAD

**Issue by richpauly13** [angular-eslint/angular-eslint#420]
**Description and reproduction of the issue**

The `@angular-eslint/builder` schematics always create an `.eslintrc.json` file.  In most situations this probably works for developers.  We, however, use the VSCode eslint extension.

We use the default `.eslintrc.json` configuration of:

root `.eslintrc.json` file:

```JSON
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": [
          "tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "extends": [
        "plugin:@angular-eslint/recommended",
        "plugin:@angular-eslint/template/process-inline-templates"
      ],
      "rules": {
        ...
      }
    },
    {
      "files": ["*.html"],
      "extends": ["plugin:@angular-eslint/template/recommended"],
      "rules": {
         ...
      }
    }
  ]
}
```

This works fine for single project.  A monorepo with multiple `.eslintrc.json` and `tsconfig.*` files that use `@typescript/eslint` rules that include type checking makes it fail.

projects.application `.eslintrc.json` file:

```JSON
{
  "extends": ["../../.eslintrc.json"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": [
          "projects/application/tsconfig.app.json",
          "projects/application/tsconfig.spec.json",
          "projects/application/e2e/tsconfig.json"
        ],
        "createDefaultProgram": true
      },
      "rules": {
         ...
      }
    },
    {
      "files": ["*.html"],
      "rules": {
        ...
      }
    }
  ]
}
```

VSCode has a red squiggly line under the first import statement of every component and does not report any linting errors.

If we change our `.eslintrc.json` to this:

projects.application `.eslintrc.json` file:

```JSON
{
  "extends": ["../../.eslintrc.json"],
  "ignorePatterns": ["!**/*"],
  "overrides": [
    {
      "files": ["*.ts"],
      "parserOptions": {
        "project": [
          "projects/application/tsconfig.*?.json"
        ],
        "createDefaultProgram": true
      },
      "rules": {
         ...
      }
    },
    {
      "files": ["*.html"],
      "rules": {
        ...
      }
    }
  ]
}
```

VSCode works again but the `@typescript/eslint` rules that include type checking fail and throw errors in VSCode requiring us to comment out those rules.  Those rules are important and some developers do not get the errors for poor coding practices.

This is due to the `@typescript/eslint/parser` requiring `tsconfigRootDir: __dirname` in the root `eslintrc.js` file.  JSON, however, does not allow for JavaScript properties such as this.

** Proposal **

Either have the `@angular-eslint/builder` schematics always create an `.eslintrc.js` file or give the user an option (similar to how Angular gives you the option to add routing if not in the ng new flags).

This option can allow the user to select the extension of the `eslintrc*` file from a list of `JSON`, `JS`, or `YAML` based on their needs, projects, and workspace.

Another option would be to default to a `.JSON` extension unless to the builder discovers the presence of a monorepo, then it would use a `eslintrc.js` extension.

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `^4.22.0` |
| `TypeScript`                       | `~4.1.5` |
| `ESLint`                           | `^7.24.0` |
| `node`                             | `14.16.1` |
| `VSCode ESLint exension` | `2.1.20`

```sh
# Please run `npx ng version` in your project and paste the full output here:

Angular CLI: 11.2.9
Node: 14.16.1
OS: win32 x64

Angular: 11.2.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.9
@angular-devkit/build-angular   0.1102.9
@angular-devkit/core            11.2.9
@angular-devkit/schematics      11.2.9
@angular/cli                    11.2.9
@schematics/angular             11.2.9
@schematics/update              0.1102.9
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.1.5

```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
A few points of clarification:

- The builder is not involved at all when linting in VSCode runs.
- The builder is not involved in code generation.
- The builder is what powers `ng lint` on the command line, it wraps the node API of ESLint in a way that the Angular CLI understands in order to execute linting via a common mechanism, instead of using the ESLint CLI directly

Regarding multi-project workspaces:

We have multiple multi-project workspaces in this repo which run integration tests on every commit.

If you clone the repo, run `yarn` and then `yarn integration-tests` then wait until all the integration tests are complete (will take a few minutes) then you will find a series of ready to use multi-project workspaces here: https://github.com/angular-eslint/angular-eslint/tree/master/packages/integration-tests/fixtures/

You can try opening VSCode at the root of any of them as if they were your main workspace, and if you make a change which violates a rule you will see inline linting feedback in VSCode.

E.g. 1

![image](https://user-images.githubusercontent.com/900523/115212879-07f65700-a112-11eb-948d-cbe8f6d08b77.png)

E.g. 2

![image](https://user-images.githubusercontent.com/900523/115213981-214bd300-a113-11eb-9f89-c809351902f0.png)


If you are experiencing issues then it is likely you are not using the setup generated by the schematics.

A full reproduction repository would be required in order to look into this any further, but hopefully the above is useful in tracking down what makes your current setup different.

Many thanks!

PS the policy around supported ESLint config file types is documented in the README: https://github.com/angular-eslint/angular-eslint#notes-on-supported-eslint-configuration-file-types

**Comment by richpauly13** [comment]
Yes I know the builder wasnt the best pick for the issue, but there was no issue place for @angular-eslint/schematics.

Believe me I am not an amateur at this.  I have been using eslint, @typescript/eslint, and @angular-eslint since they first came out and have watched the tech mature until now.

If you read closely, the system all works as expected for the setup you have, but when manual overrides for @typescript/eslint/parser are added is when VSCode fails.  Specifically when type checking is involved.

The issue comes from your schematics building .json files for the .eslintrc configs.  This works for 80% of the eslint rules, but fails on type checked rules as stated above.

I have researched this issue for the past 6 months before I found out the only way to over come this is to use a .eslintrc.js config.  Specifically the typescript eslint parser requires the option of tsconfigRootDir: __dirname in the main root .eslintrc.js file which cant be used with .json.

I have already upgraded the repo to use all .eslinrc.js files, but you can clone the repo from previous commits here:  https://github.com/richpauly13/easy/tree/127e9bf8230de207f0533d3f7b6f4ef82e42f35c to see the issue.  You will need to uncomment the @typescript/eslint rules that I have commented out to see the issue in VSCode.

Then compare that to the current config that I have now here:  https://github.com/richpauly13/easy.

You will see the only difference is that I changed the eslint config files to .js and added the tsconfigRootDir: __dirname option to the root eslint.rc.js file.

**Comment by JamesHenry** [comment]
@richpauly13 I cloned your repo and checked out the commit which uses the JSON files.

You simply have a typo in there which is causing your issues:

![image](https://user-images.githubusercontent.com/900523/115374715-275ab600-a1de-11eb-8695-aa6f5e0154cb.png)

After applying that fix, everything works as expected with the rule you had commented out:

![image](https://user-images.githubusercontent.com/900523/115374800-3b061c80-a1de-11eb-9ff4-4d2f5d8cbf05.png)

**Comment by richpauly13** [comment]
strange I still get this

![image](https://user-images.githubusercontent.com/8948337/117553705-a6dae880-b018-11eb-843e-074781c163cf.png)
