### ISSUE TITLE
`Program#body` is missing and breaks a lot of other rules

### ISSUE THREAD

**Issue by JounQin** [angular-eslint/angular-eslint#476]
**Description and reproduction of the issue**

As title

`body` is required in `estree`

https://github.com/estree/estree/blob/master/es2015.md#programs

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/estree/index.d.ts#L65

**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@typescript-eslint       `        | `4.24.0` |
| `TypeScript`                       | `4.2.4` |
| `ESLint`                           | `7.26.0` |
| `node`                             | `12.22.1` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 12.0.0
Node: 12.22.1
Package Manager: yarn 1.22.10
OS: darwin x64

Angular: 12.0.0
... compiler, core

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1200.0 (cli-only)
@angular-devkit/core         12.0.0 (cli-only)
@angular-devkit/schematics   12.0.0 (cli-only)
@schematics/angular          12.0.0 (cli-only)
rxjs                         7.0.1
typescript                   4.2.4
```

- [x] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Comment by JamesHenry** [comment]
@JounQin Can you please give me an example of rules it breaks? This is not an `ESTree` AST and the `template-parser` should only be used on HTML files via config overrides as per the README.

**Comment by JounQin** [comment]
@JamesHenry

It is very common to use top level ESLint rules without `overrides`, although it is not recommended in `@angular-eslint`.

For example:

```js
module.exports = {
  extends: ['plugin:unicorn/recommended', 'plugin:prettier/recommended'],
  overrides: [
    {
      files: '*.ts',
      extends: [
        'plugin:@angular-eslint/recommended',
        'plugin:@angular-eslint/template/process-inline-templates',
      ],
    },
    {
      files: ['*.html'],
      extends: ['plugin:@angular-eslint/template/recommended'],
      rules: {
        'prettier/prettier': 0,
      },
    },
    {
      files: ['*.html'],
      excludedFiles: ['*inline-template-*.component.html'],
      rules: {
        'prettier/prettier': [
          'error',
          {
            parser: 'angular',
          },
        ],
      },
    },
  ],
}
```

**Comment by JamesHenry** [comment]
@JounQin I don't get any issues with Program.body not existing with that config?

Again this is a fundamentally different file type - not supported by ESLint directly - and requires a totally different parser and AST, that's just how it is.

The root level pseudo "Program" node exists purely so that location information can flow through ESLint's assumptions correctly, it is not related to an attempted compliance with the ESTree spec, that is impossible in the case of Angular-flavoured HTML

**Comment by JamesHenry** [comment]
> I understand that, it is very common usage, but ESLint should parse estree compatibly so that other rules will just skip correctly.

The thing is, they aren't "skipping" it. All this "fix" will do is hide the fact that you have a misconfigured project. All those rules will still be loaded _and_ executed (not skipped) for files they should have nothing to do with, making your lint run slower and more memory intensive than it needs to be.

I will merge your PR, but I strongly encourage you to address your real issue which is that your eslint config should be updated to point the right rules and plugins at the right files. I explain this in great detail in the README.

**Comment by JamesHenry** [comment]
Actually, sorry for the confusion, I have changed my mind.

It is preferable to help users through hard to understand error messages (combined with the already comprehensive README on this topic), than to merge something which will mask configuration issues.

There is simply no reason why your configuration cannot be updated with the exact same rules and plugins, but with them applied to the correct file types.

Thank you for contributing though, and for the helpful discussion to find a resolution.

**Comment by JounQin** [comment]
My `skip` means `skipped in the rules`.

I understand your concerning, but it is very common usage to use ESLint config presets, what `template-parser` requiring(`overrides` for all files) makes top level `extends` and `rules` unusable at all, but the fact is, we just want to enable `*.html` linting, why should we change all ESLint configs.

Here is my sharable ESLint configs for example.

https://github.com/1stG/configs/pull/22/files

**Comment by JamesHenry** [comment]
I agree with you on what is common, and on what is not. Angular-flavoured HTML linting is _very_ uncommon. In fact there was no HTML linting at all before this project, that is how uncommon it is. `eslint-plugin-html` deals with linting JavaScript within `<script>` tags.

Therefore there are trade-offs in making it all work together.

For your shareable configs, you can create them in "flat" way, with things applied at the top-level, e.g. 

`@jounqin-shareable-configs/angular-template` [SHAREABLE - FLAT IS FINE]

```json
{
  "parser": "@angular-eslint/template-parser",
  "plugins": ["@angular-eslint/template"],
  "rules": {
     "@angular-eslint/template/banana-in-box": "error",
    "@angular-eslint/template/eqeqeq": "error",
    "@angular-eslint/template/no-negated-async": "error"
  }
}

```

`@jounqin-shareable-configs/typescript` [SHAREABLE - FLAT IS FINE]

```json
{
  "parser": "@typescript-eslint/parser",
  "plugins": ["@typescript-eslint", "@angular-eslint"],
  "rules": {
    "@typescript-eslint/no-non-null-assertion": "error",
    "@angular-eslint/use-lifecycle-interface": "warn"
  }
}

```

`jounqin-app/.eslintrc.json` [ACTUAL PROJECT - USE OVERRIDES]

```json
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "overrides": [
    {
      "files": "*.ts",
      "extends": [
        "plugin:@jounqin-shareable-configs/typescript",
        "plugin:@angular-eslint/template/process-inline-templates"
      ]
    },
    {
      "files": ["*.html"],
      "extends": ["plugin:@jounqin-shareable-configs/angular-template"]
    }
  ]
}
```

This ensures that even with shareable configs, they are composed together in the correct way for all these different parsers, plugins and rules to work together in the same lint run.

Hope that helps!

**Comment by JounQin** [comment]
@JamesHenry 

What I want is a simple ESLint config for all projects, not FLAT configs, they're too verbose:

```jsonc
// .eslintrc
{
  "extends": "@1stg"
}
```

If you don't want to add `body: []` strongly, that's fine, I will just create a `angular-eslint-template-parser` package wrapping `@angular-eslint/template-parser` and adding `body: []` into the AST instead.

**Comment by JamesHenry** [comment]
@JounQin Ok, well that is still perfectly achievable with what I wrote above, you just need to use the overrides correctly within your shareable config. 

I'm struggling to understand why you find:

YOUR PROPOSAL - `@1stg` shareable config

```jsonc
{
  "plugins": ["foo"],
  "extends": ["bar"]
  "overrides": [
    {
      "files": ["*.html"],
      // ... etc
    }
  ]
}
```

...so much more desirable than:

MY PROPOSAL - `@1stg` shareable config

```jsonc
{
  "overrides": [
    {
      "files": ["*.ts", ".js"],
      "plugins": ["foo"],
      "extends": ["bar"]
      // ... etc
    },
    {
      "files": ["*.html"],
      // ... etc
    }
  ]
}
```

Either way the project usage is still just:

```
// .eslintrc
{
  "extends": "@1stg"
}
```

Except in one of them the correct rules and plugins are applied to the correct file type.

Is there something I'm missing on the above?

**Comment by JounQin** [comment]
@JamesHenry

Top level rules are useful to enable/disable global rules, maybe a `files: '*.*'` will work, but this will be wrong to run on an invalid file ext, and for normal overrides, we have to do copies like:

```js
const globalRules = {
  // ...
}

module.exports = {
  overrides: [
    {
      files: '*.js',
      rules: {
        ...globalRules,
        // js spec rules
      },
    },
    {
      files: '*.ts',
      rules: {
        ...globalRules,
        // js spec rules
      },
    },
    // ... a lot of other rules
  ],
}
```

The above will work, but why we have to do like this, I'd prefer top level rules, performance(rules `.js` files are actually meaningless for `.html` files) is not the key point to me.

**Comment by JamesHenry** [comment]
> run on an invalid file ext

ESLint doesn't choose what file extensions to run on, so this is not really a concern. You control what file extensions ESLint runs on when you invoke it (either via the eslint CLI or ng lint), it is decoupled from config.

> we have to do copies like:

No, in my example directly above I showed the array of multiple matching file types combined into a single config block, there is not limit to the number of extensions you can combine together into a single block of config within overrides

**Comment by JounQin** [comment]
> No, in my example directly above I showed the array of multiple matching file types combined into a single config block

I mean `*.*`

---

And I have to maintain the list when I'm adding/removing languages.

We prefer different usages, that's OK, but I think the parser should not enforce what the users want to do, it's my/their own choice.

**Comment by JamesHenry** [comment]
It's just that I have to consider the impact on the community as a whole...

These packages are downloaded over 1 million times per month and this is the first time this request has ever come up. That combined with the fact it removes a piece of user feedback that currently exists with regardless to inadvertently imprecise setups means I have to objectively lean towards not making the change right now.

> And, estree compatible is very important IMO, every js parser should be estree compatible

This stance sounds good in theory, but precludes the use of **any** non-JS usage with ESLint. `typescript-eslint` is also not fully compliant with `ESTree` because it cannot be by definition. When I created the project I had to add all kinds of node types which are not part of the `ESTree` spec.

There is a trade-off between some sense of "correctness" and making things work so that a huge community of people can benefit from a combination of tools that were never intended to work together, but which do.

Ultimately what that means is the tooling needs to _make ESLint happy_ not concern itself with some arbitrary compliance with a specification that by definition does not apply to TypeScript, markdown, graphql, angular-flavoured HTML etc.

TypeScript is JavaScript-like, so in that project we work really hard to align the entirety of the AST. Angular HTML is nothing like JavaScript.

In this case, it turns out, to keep ESLint happy we need to have `Program#tokens` - that is not the case for `Program#body`.

**Comment by JamesHenry** [comment]
If this request or anything remotely close to it comes up again from the community, you have my word that I will reconsider this change, or if there is a way to achieve something similar. In the meantime, I have explained at great length how you can resolve any issues using standard ESLint configuration and the tooling as it exists today.

Thank you again for you contributions and engagement! 🙏

**Comment by JounQin** [comment]
> This stance sounds good in theory, but precludes the use of any non-JS usage with ESLint. typescript-eslint is also not fully compliant with ESTree because it cannot be by definition. When I created the project I had to add all kinds of node types, node properties and their values, which are not part of the ESTree spec.

Compatible with estree does not mean what you said IMO. For same source text, different parsers should produce standard AST, so the users can easily change different compatible parsers. For example, for standard js, the default ESLint parser, `@babel-eslint/parser` and `@typescript-eslint/parser` should work just the same.

https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/typescript-estree#about

> In this case, it turns out, to keep ESLint happy we need to have Program#tokens - that is not the case for Program#body.

Now, other rules using `Program#body` is not happy due to just an estree standard property.

---

Never mind, I'm working on https://github.com/rx-ts/angular-eslint-template-parser instead now.

**Comment by JamesHenry** [comment]
@JounQin This will be my last message on this topic. I have done my best to stay polite, objective and on topic but you don't seem to want to meet me half-way.

- We are talking about `@angular-eslint/template-parser`, not something designed to work on a JS-like source so you are taking the discussion to a place it shouldn't be by referencing JS-like parsers. It is apples to oranges. If there were multiple HTML eslint parsers to compare, then and only then would AST comparisons for the same sources be relevant.
- I created one of the parsers you reference, and I have worked on the other. I also literally created the document you are linking to.

But let's follow your comment about how all eslint parsers should work the same on the same source through to completion and actually bringing in the parser in question -`@angular-eslint/template-parser` - as well as another completely unrelated parser that is designed to work on neither JS-like sources, nor Angular HTML: `@graphql-eslint/eslint-plugin` (that exposes the grapqhl ESLint parser https://github.com/dotansimha/graphql-eslint#configuration).

> For same source text, different parsers should produce standard AST, so the users can easily change different compatible parsers

Your statement suggests `@angular-eslint/template-parser` or `@graphql-eslint/eslint-plugin` or any other eslint parser which unlocks the ability to lint non-JS sources should parse this and return an ESTree AST that is compatible with `espree`, `@typescript-eslint/parser` etc.

```js
var foo = true;
```

But, of course, that is not what happens. In the case of the `@graphql-eslint/eslint-plugin`, you logically get:

```sh
1:1  error  Parsing error: [graphql-eslint]: Syntax Error: Unexpected Name "var"
```

The exact same thing is true if you feed HTML sources to one of the JS-like parsers you reference - they will throw a Parse Error because they were not intended to work on those sources.

Therefore, your statement:

> For same source text, different parsers should produce standard AST, so the users can easily change different compatible parsers

...cannot possibly be correct, unless you ban the use of all non-JS sources with ESLint, as I have stated many times on this thread now.

> Now, other rules using Program#body is not happy due to just an estree standard property.

**Only if you use them how they weren't intended to be used** - on non-JS like files. For example, graqhql or Angular-flavoured HTML. **If you use those rules as they were intended to be used**, then they work just fine, including when combined with non-JS parsers, plugins and rules such as graphql or Angular-flavoured HTML in a single lint run, because `overrides` was designed for exactly this reason.

**Comment by JounQin** [comment]
I appreciate your replies and statements, and understand `overrides` is preferred in your mind, but please don't misunderstand my point, all I'm talking about is `estree` compatibility with other rules, not how `html` should be parsed in ESLint by other parsers.

And I've given up by

> Never mind, I'm working on rx-ts/angular-eslint-template-parser instead now.
