### ISSUE TITLE
[Rule Request] can we migrate `angular-whitespace` from codelyzer ?

### ISSUE THREAD

**Issue by Emeryao** [angular-eslint/angular-eslint#602]
since pritter is too opinionated for me and does not do the job well as the rule of angular-whitespace

**Comment by rafaelss95** [comment]
We have no plans to migrate it (or add any other formatting rule), first because codelyzer's `angular-whitespace` rule was [deprecated](https://github.com/mgechev/codelyzer/blob/8b7d153e737d0978a9aaa852beb32aad3345eb3b/src/angularWhitespaceRule.ts#L283). For more context: https://github.com/mgechev/codelyzer/issues/719.

We have already discussed about it some other times like: https://github.com/angular-eslint/angular-eslint/issues/124#issuecomment-685041448, https://github.com/angular-eslint/angular-eslint/issues/286#issuecomment-798881652, #219 and https://github.com/angular-eslint/angular-eslint/discussions/564.

Finally, you can check the dedicated document about [**Our philosophy on lint rules which enforce code formatting conventions**](https://github.com/angular-eslint/angular-eslint/blob/master/docs/FORMATTING_RULES.md.
