### ISSUE TITLE
Adding linter to multi-project workspace results in incomplete/broken configuration

### ISSUE THREAD

**Issue by drullo** [angular-eslint/angular-eslint#632]
# 🐞 Bug report

## Description

When adding `@angular-eslint/schematics` to a workspace that was initially created with `--create-application=false`, the `.eslintrc.json` files are not added to the workspace root, or to the project directories (_if projects exist_) and the **architect/lint** sections are not added to project definitions in `angular.json` regardless of whether the projects are created before or after adding `@angular-eslint/schematics`.

## Minimal Reproduction

```
ng new workspace --create-application=false
cd workspace
ng add @angular-eslint/schematics
ng generate library lib1
```

## Exception or Error

When attempting to run the linter, the following error is produced even after the above steps are performed

<pre><code>
Cannot find "lint" target for the specified project.

You should add a package that implements linting capabilities.

For example:
  ng add @angular-eslint/schematics

</code></pre>

## Environment
* Windows 10
* @angular/cli 12.1.4

<pre><code>
Angular CLI: 12.1.4
Node: 14.16.0
Package Manager: npm 7.21.0
OS: win32 x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/cli                    12.1.4
@schematics/angular             12.1.4
ng-packagr                      12.2.1
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

## Additional Information

It seems that adding the linter to a single-project workspace, which later includes additional projects, results in success and covers all projects as expected.

**Comment by bogacg** [comment]
You need to execute once more `ng add @angular-eslint/schematics` for it to work it's magic. First execution only adds packages, after you create your lib/app by executing that command for the second time it understands what it has to do.

However the situation is still not perfect. That second execution generates an `eslintrc.json` under lib/app with ` "extends": "../../.eslintrc.json",` being its first option which is kind of faulty since `ng add @angular-eslint/schematics` did not generate that root file in neither execution so you get error. Removing that `extends` option makes things work partially.

In my case after removing  `extends` option I could see some errors in TS files as expected but not the errors in templates.

**Comment by zah33r** [comment]
> You need to execute once more `ng add @angular-eslint/schematics` for it to work its magic. First execution only adds packages, after you create your lib/app by executing that command for the second time it understands what it has to do.
> 
> However the situation is still not perfect. That second execution generates an `eslintrc.json` under lib/app with ` "extends": "../../.eslintrc.json",` being its first option which is kind of faulty since `ng add @angular-eslint/schematics` did not generate that root file in neither execution so you get error. Removing that `extends` option makes things work as far as I can see.
> 
> It's already reported #462

I have tried to execute it multiple times, but it seems to update only package.json and package-lock.json files. no eslintrc.json is generated nor the angular.json is updated for my workspace projects. 

Steps I performed:
a) created empty workspace without a project
b) generated an application which created in projects directory
c) created the library project in the workspace, again created inside projects directory
d) executed command `ng add @angular-eslint/schematics` at the angular.json directory level

Root folder doesn't have any **src** folder, which I believe is the root cause of this.

However I created a blank new project and eslint all are working in angular 13 with `ng add @angular-eslint/schematics`. 
I am trying to do these steps manually(copy/pasting file .eslintrc.json and changing cli key with lint object in angular.json) but still no luck.

**Comment by tgfactor** [comment]
I can concur.  I'm creating a new workspace and project with Angular 13.  I have a default project created, and when I added the angular-eslint/schematics project, it proceeded to only add the eslintrc file in the project root folder, not the workspace folder as well, which the project eslintrc extends.  This is forcing me to have to create an additional eslintrc file manually in the workspace root just to get the eslint to work correctly.

**Comment by JamesHenry** [comment]
Thanks folks, I'm pleased to say that the `--create-application=false` case is now supported automatically as of `13.2.0`
