### ISSUE TITLE
[sort-ngmodule-metadata-arrays] `--fix` not able to correct all the reports once

### ISSUE THREAD

**Issue by splincode** [angular-eslint/angular-eslint#675]
```JSON
{
  "rules": {
    "@angular-eslint/sort-ngmodule-metadata-arrays": "error"
  }
}
```

After run with `--fix` didn't work for my cases:

```ts
// ...

@NgModule({
    imports: [
        CommonModule,
        DeepPathPipeModule,
        DefaultValuePipeModule,
        DragDropModule,
        MatIconModule,
        MergeCssClassesPipeModule,
        SafePipeModule
    ],
    declarations: [
        AutoHeightDirective,
        NgxColumnComponent,
        NgxOptionsComponent,
        TableBuilderComponent,
        TableTbodyComponent,
        TableTheadComponent,
        TableCellComponent,
        TemplateBodyTdDirective,
        TemplateHeadThDirective,
        ObserverViewDirective,
        NgxContextMenuComponent,
        NgxContextMenuItemComponent,
        NgxContextMenuDividerComponent,
        NgxMenuContentComponent,
        NgxEmptyComponent,
        NgxHeaderComponent,
        NgxFooterComponent,
        NgxFilterViewerComponent,
        NgxFilterComponent,
        NgxFilterDirective,
        DragIconComponent,
        NgxSourceNullComponent,
        DisableRowPipe,
        TableSelectedItemsPipe,
        MapToTableEntriesPipe,
        VirtualForDirective,
        GetFreeSizePipe,
        GetClientHeightPipe
    ],
    providers: [WebWorkerThreadService],
    exports: [
        NgxColumnComponent,
        NgxOptionsComponent,
        NgxContextMenuComponent,
        TableBuilderComponent,
        TemplateBodyTdDirective,
        TemplateHeadThDirective,
        NgxContextMenuItemComponent,
        NgxContextMenuDividerComponent,
        NgxMenuContentComponent,
        NgxEmptyComponent,
        NgxHeaderComponent,
        NgxFooterComponent,
        NgxFilterViewerComponent,
        NgxFilterComponent,
        NgxFilterDirective,
        TableSelectedItemsPipe,
        MapToTableEntriesPipe,
        NgxSourceNullComponent
    ]
})
// ...
```

**Versions**

| package                                   | version |
| ----------------------------------        | ------- |
| `@angular-eslint/eslint-plugin`  | 12.3.1 |
| `@typescript-eslint/parser`               | 4.31.0 |
| `ESLint`                                  | 7.32.0 |
| `node`                                    | 16.0 |

**Comment by splincode** [comment]
also

![image](https://user-images.githubusercontent.com/12021443/132715045-0a6c52b1-50be-487d-b80e-69c4aa8c3220.png)


```ts
import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { MatListModule } from '@angular/material/list';
import { MatMenuModule } from '@angular/material/menu';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatToolbarModule } from '@angular/material/toolbar';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { FlexLayoutModule } from '@angular-ru/cdk/flex-layout';

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';

@NgModule({
    declarations: [AppComponent],
    imports: [
        AppRoutingModule,
        BrowserModule,
        FlexLayoutModule,
        HttpClientModule,
        MatListModule,
        MatMenuModule,
        MatSidenavModule,
        MatToolbarModule,
        BrowserAnimationsModule
    ],
    bootstrap: [AppComponent]
})
export class AppModule {}
```

**Comment by splincode** [comment]
@timdeschryver could you help me?

**Comment by rafaelss95** [comment]
Hi @splincode, I'm not Tim, but I'll try to help you :vulcan_salute:

The fixer itself indeed works as you can see here (and in many other places in the file mentioned below), for example:

https://github.com/angular-eslint/angular-eslint/blob/b38d82894ed39358a48c4689dd79749ad9216dc1/packages/eslint-plugin/tests/rules/sort-ngmodule-metadata-arrays/cases.ts#L82-L99

---

The problem you might be facing is that, as described [at the official ESLint documentation](https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes), the fixer _process will repeat up to 10 times, or until no more fixable problems are found_. In other words, to completely fix the code you showed us above, according to this rule, you would need more than 10 iterations and that's why you still see report problems.

On the other hand, I can see that the algorithm that finds unordered nodes can be improved to avoid as many iterations as currently: 

https://github.com/angular-eslint/angular-eslint/blob/f99306977254e2894ad769448f0cbebd7665cbcd/packages/eslint-plugin/src/rules/sort- ngmodule-metadata-arrays.ts # L36-L41

But note that, depending on how many changes are needed, you'll still hit the 10-limit problem.

**Comment by splincode** [comment]
`But note that, depending on how many changes are needed, you'll still hit the 10-limit problem.` 
https://github.com/lydell/eslint-plugin-simple-import-sort
Yes, but rule `import sort` works without 10 iterations, I expect the same behavior ))

`On the other hand, I can see that the algorithm that finds unordered nodes can be improved to avoid as many iterations as currently`

Can you improved this code?

`Use the real version instead of latest` fixed

**Comment by JamesHenry** [comment]
Thanks all, closing in favour of #1232 please subscribe to that issue for updates
