### ISSUE TITLE
Trying to figure out configuration for our angular project

### ISSUE THREAD

**Issue by stonecourier** [angular-eslint/angular-eslint#802]
**Versions**

| package                            | version |
| ---------------------------------- | ------- |
| `@angular-eslint/builder`          | `12.6.1` |
| `ESLint`                           | `7.26.0` |
| `node`                             | `16.13.0` |

```sh
# Please run `npx ng version` in your project and paste the full output here:
Angular CLI: 12.2.12
Node: 16.13.0 (Unsupported)
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 12.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.9
@angular-devkit/build-angular   12.2.12
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.9
@schematics/angular             12.2.9
ng-packagr                      12.2.5
rxjs                            7.4.0

```

- [ X] I have updated to the latest supported version of the packages and checked my `ng version` output per the instructions given here.

**Description and reproduction of the issue**

So I have read the notes on the performance, and tried all the debug logic and we are now getting good linting performance when using a custom tsconfig file.

![image](https://user-images.githubusercontent.com/2016796/141718113-56c745c6-8721-4292-a0c2-935b9de7de34.png)

![image](https://user-images.githubusercontent.com/2016796/141719822-d6e785a4-b697-409f-bc07-348af45d60e9.png)

We currently have 4 angular projects in a mono repo, using shared library modules. We are not using Nx.

![image](https://user-images.githubusercontent.com/2016796/141718263-90cd6c05-09d7-4055-8b50-3976297eb9d4.png)

In the angular.json, if we change the linting pattern to include the libraries folder (just the ts file), it works and lints the library files as well. If we include the html files, it gets the problem with generating programs over and over. Is there something we can include in the config paths to fix this.

![image](https://user-images.githubusercontent.com/2016796/141718391-83b2dffc-0683-4250-9340-ff83ddf5ba3d.png)

![image](https://user-images.githubusercontent.com/2016796/141719944-51f8795d-494b-4f8b-b569-0e0ee02e3a94.png)

**Comment by sagrawal31** [comment]
I also have the same issue. **The default configuration generated by this library is not performant**. I have a monorepo with 2 apps & 2 libs. If I run eslint for one app `time DEBUG=typescript-eslint:* ng lint client-app` with the default configuration generated by this schematic, here is the time taken-

```
All files pass linting.

DEBUG=typescript-eslint:* ng lint client-app  228.54s user 43.00s system 110% cpu 4:06.59 total
```

Because, for every file, it waits for a fraction of seconds after the second line in the screenshot-

![image](https://user-images.githubusercontent.com/1804514/153848657-490cdc0e-021e-4133-b0df-2c3aa634a6f2.png)

This seems to be because of `include` pattern in `tsconfig.app.json` in `projects/client-app` as it include `"src/**/*.d.ts"`. 

So I have two options to improve the performance-

### Solution 1

Change the line `"src/**/*.d.ts"` to `"src/**/*.ts"` in `projects/client-app/tsconfig.app.json` and here is the output-

```
All files pass linting.

DEBUG=typescript-eslint:* ng lint client-app  17.67s user 1.29s system 156% cpu 12.099 total
```

**Significant drop from 228 seconds to 17 seconds**

But not sure what side-effects it will have in the TS compiler.

### Solution 2

Create a `tsconfig.eslint.json` in the root folder to include all the ts files-

```json
{
    "extends": "./tsconfig.json",
    "include": [
        "**/src/**/*.ts",
        "**/src/**/*.html"
    ]
}
```

Remove followings from `projects/client-app/.eslintrc.json`-

```
"parserOptions": {
    "project": [
        "projects/fuse-lib/tsconfig.lib.json",
        "projects/fuse-lib/tsconfig.spec.json"
    ],
},
```

And add the following in the root `.eslintrc.json` inside `overrides`-

```
"parserOptions": {
    "project": [
        "tsconfig.eslint.json"
    ],
    "createDefaultProgram": true
},
```

Again, not sure what side-effect will it cause to point all the files in the `tsconfig.eslint.json`.

**Comment by q-garethallenstringer** [comment]
@sagrawal31 solution 1 and 2 both worked for me, but 1 broke my build! trouble was, solution 1 meant test types couldn't be found however for solution 2 everything still seems to work fine.

**Comment by vixero-dev** [comment]
Solution 2 fixed the performance issues I had. I have an Angular workspace with 3 projects.

**Comment by JamesHenry** [comment]
Hi Folks, closing this one for housekeeping reasons as it is very old now and in the meantime the default setup of angular-eslint does not include any type-checking, so the performance is significantly faster OOTB
