### ISSUE TITLE
Can we use semantic versioning with these packages?

### ISSUE THREAD

**Issue by pbrianmackey** [angular-eslint/angular-eslint#864]
It is clear from the [supported versions documentation](https://github.com/angular-eslint/angular-eslint#supported-angular-cli-versions) that we can use semver `^12.7.0` w/ Angular 12 because the docs say:

>  the exact minor and patch versions of each library represented here by x's do not need to match each other, just the first (major) number

Please also explain if and how we can safely apply semver to these packages that are also included with @angular-eslint:

    "@typescript-eslint/eslint-plugin": "4.28.2",
    "@typescript-eslint/parser": "4.28.2",

The installer `ng add @angular-eslint/schematics` didn't use semver.  All the packages were fixed.

**Comment by BeGj** [comment]
I added semantic versioning like this guy, and it works currently... #865 
```
    "@angular-eslint/builder": "^13.0.1",
    "@angular-eslint/eslint-plugin": "^13.0.1",
    "@angular-eslint/eslint-plugin-template": "^13.0.1",
    "@angular-eslint/schematics": "^13.0.1",
    "@angular-eslint/template-parser": "^13.0.1",
    "@typescript-eslint/eslint-plugin": "^5.10.2",
    "@typescript-eslint/parser": "^5.10.2",
```

**Comment by JamesHenry** [comment]
@pbrianmackey Sorry for the delayed response, I'll outline my thinking below.

I'm not trying to be overly pedantic, but to say that it "didn't use semver" doesn't really make sense to me. All of the versions shown are from packages which follow semantic versioning (as does angular-eslint itself), aka semver, which means that the structure of the versions convey a meaning, i.e. `MAJOR.MINOR.PATCH`.

In general the versions we generate for you are fixed, yes, because fixed versions are less vulnerable to exposure to package exploits and other issues. There could be a whole debate about that train of thought and what the tooling generates for you out of the box, but, importantly, you are not tied to what it generated for you - you can change it to whatever your preference is (like @BeGj has done above).

Naturally, you should try and avoid changing the major versions of key dependencies related to these packages, such as Angular, TypeScript and ESLint (because they will likely require some migrating which will need to be done in angular-eslint anyway), but patch versions should certainly be ok, and more often than not minor versions will be as well.

Hope that helps!
