### ISSUE TITLE
Type-check rules cause errors when using `ng lint`

### ISSUE THREAD

**Issue by delasteve** [angular-eslint/angular-eslint#89]
### Steps to reproduce

1. Run the commands
    ```
    ng new sample-application
    ng add @angular-eslint/schematics
    ```

1. Change `angular.json`'s `projects:sample-app:architect:lint` property to:
    ```json
	"lint": {
	  "builder": "@angular-eslint/builder:lint",
	  "options": {
	    "eslintConfig": ".eslintrc.js",
	    "tsConfig": [
	      "tsconfig.app.json",
	      "tsconfig.spec.json",
	      "e2e/tsconfig.json"
	    ],
	    "exclude": ["**/node_modules/**"]
	  }
	},
    ```

1. Create a `.eslintrc.js` file with:
	```js
	module.exports = {
	  extends: [
	    // comment this next line out to see no errors occur
	    "plugin:@typescript-eslint/recommended-requiring-type-checking",
	    "plugin:@angular-eslint/recommended",
	  ],
	  plugins: ["@typescript-eslint", "@angular-eslint"],
	};
	```
1. Run the command
    ```
    ng lint
    ```

### Output

```
An unhandled exception occurred: Error while loading rule '@typescript-eslint/await-thenable': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting 
```

### Other notes

I created a repository to reproduce this issue. It can be found here: https://github.com/delasteve/eslint-angular-issue-sample-repo

I'm also trying to figure out if this next error is an `angular-eslint` issue or something else. If you swap the order of the extends array so that `plugin:@angular-eslint/recommended` is first, you will receive the following error:

```
D:\development\sample-app\src\app\app.component.html
  0:0  error  Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src\app\app.component.html.
The extension for the file (.html) is non-standard. You should add "parserOptions.extraFileExtensions" to your config
```

**Comment by IAMtheIAM** [comment]
It tells you that you need parserOptions.project. Try adding something like this to your .eslintrc.js

```
    "parserOptions": {
        "ecmaVersion": 2020, // Allows for the parsing of modern ECMAScript features
        "project": "tsconfig.json",
        "sourceType": "module"
    },
```

**Comment by delasteve** [comment]
@IAMtheIAM, I would expect the builder to inject that for you given that we define the tsconfigs in the `angular.json` file.

That said, I did what you suggested and it doesn't work. I tried with both `tsconfig.json` and `tsconfig.app.json`. Both resulted in the following

![image](https://user-images.githubusercontent.com/595925/82731811-40f63380-9cd7-11ea-81ec-51054402faf6.png) 

`.eslintrc.js`
```js
module.exports = {
  parserOptions: {
    ecmaVersion: 2020, // Allows for the parsing of modern ECMAScript features
    project: "tsconfig.app.json",
    sourceType: "module",
  },
  extends: [
    // comment this next line out to see no errors occur
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:@angular-eslint/recommended",
  ],
  plugins: ["@typescript-eslint", "@angular-eslint"],
};
```

**Comment by IAMtheIAM** [comment]
@delasteve After spending many hours yesterday working on typescript-eslint configuration issues, I learned several things that I think will solve you issues:

1) Since you are using rules that require type information, and because the parserOptions.project property does NOT inherit the base `tsconfig.json` from the `extends` option inside your `tsconfig.app.json`, then you need to specify your `tsconfig.json` in addition to `tsconfig.app.json` inside your parserOptions.project array. [See here](https://www.npmjs.com/package/@typescript-eslint/parser#parseroptionsproject) for more info - it explains this. Therefore, change this:

```
  parserOptions: {
    ecmaVersion: 2020, // Allows for the parsing of modern ECMAScript features
    project: "tsconfig.app.json",
    sourceType: "module",
  },
```

to
```
  parserOptions: {
    ecmaVersion: 2020, // Allows for the parsing of modern ECMAScript features
    project: ["tsconfig.json", "tsconfig.app.json"] // this should be an array which includes all required tsconfig.json files
    sourceType: "module",
  },
```

Your second issue regarding the error `The file does not match your project config: src\app\app.component.html. The extension for the file (.html) is non-standard. You should add "parserOptions.extraFileExtensions" to your config` - that is due to a tsconfig.json configuration issue. You did not post it here, but I assume you did not include the `include` option to specifically specify only *.ts files. Here is an example of my working `tsconfig.json` file

```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
        "downlevelIteration": true,
        "importHelpers": true,
        "outDir": "./dist/compiled",
        "sourceMap": true,
        "allowSyntheticDefaultImports": true,
        "declaration": false,
        "module": "esnext",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "target": "es2015",
        "typeRoots": [
            "node_modules/@types"
        ],
        "types": [
        ],
        "lib": [
            "es2018",
            "es2015",
            "es2016",
            "dom",
            "es5",
            "es6"
        ]
    },
    "include": [
        "**/*.d.ts",
        "**/*.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```
As you can see, you need to `include` the type of files typescript should be checking, otherwise I believe it defaults to all files in the `baseUrl` which would cause your issue regarding the error about `app.component.html`. TypeScript should not be reading files with `.html` or `.css` extensions, etc.

In addition, there is really no reason for having a separate `tsconfig.app.json` if you have only one single UI within your project. The only purpose of it is if you have multiple angular applications living in one monorepo, and you need to specify different typescript configuration for each. I would personally  just merge the needed config options (if any) from the `tsconfig.app.json` into `tsconfig.json`. If you do that, make sure to update your `angular.json` `lint.options.tsConfig` array
```
"lint": {
  "builder": "@angular-eslint/builder:lint",
  "options": {
    "eslintConfig": ".eslintrc.js",
    "tsConfig": [
      "tsconfig.json",
      "tsconfig.spec.json", // you don't need this unless you want to lint your karma tests at the same time as your main application
      "e2e/tsconfig.json" // you don't need this either unless you want to lint your e2e tests at the same time as your main application. I would separate these into their own `lint:e2e` and `lint:spec` builder options.
    ],
    "exclude": ["**/node_modules/**"]
  }
},
```

Let me know if any of this works for you.

**Comment by IAMtheIAM** [comment]
As a last resort, if none of that works, please try creating a new npm script that bypasses the angular cli and directly call eslint. For example, update the scripts like this:
```
        "lint:es": "eslint './**/*.ts'",
        "lint:ng": "ng lint",
```
and then on your command line call `npm run lint:es` instead of `ng:lint`

Sidenote, if you want to see the time each rule of eslint takes, install `cross-env` first `npm i -d cross-env` and then pass in the env variable `TIMING`. You can also pass `--fix` to automatically fix many issues.
```
        "lint": "cross-env TIMING=1 eslint './**/*.ts' --fix",
        "lint:ng": "cross-env TIMING=1 ng lint --fix",
```

**Comment by IAMtheIAM** [comment]
Side note: There is really no reason for having a separate tsconfig.app.json if you have only one single UI within your project. The only purpose of it is if you have multiple angular applications living in one monorepo, and you need to specify different typescript configuration for each. 

You can simplify your configuration a little. I would personally just merge the needed config options (if any) from the tsconfig.app.json into tsconfig.json. If you do that, make sure to update your angular.json config section lint.options.tsConfig array and also your parserOptions.project array
```
"lint": {
  "builder": "@angular-eslint/builder:lint",
  "options": {
    "eslintConfig": ".eslintrc.js",
    "tsConfig": [
      "tsconfig.json",
      "tsconfig.spec.json", // you don't need this unless you want to lint your karma tests at the same time as your main application
      "e2e/tsconfig.json" // you don't need this either unless you want to lint your e2e tests at the same time as your main application. I would separate these into their own `lint:e2e` and `lint:spec` builder options.
    ],
    "exclude": ["**/node_modules/**"]
  }
},
```

However, webpack might complain of unused imports if you have any .ts files in your repo that are not imported anywhere. Just an FYI.

**Comment by delasteve** [comment]
>There is really no reason for having a separate tsconfig.app.json if you have only one single UI within your project

@IAMtheIAM - I would like to believe major changes to the CLI's default project layout are out of scope for this issue as well as this project.

**Comment by IAMtheIAM** [comment]
That's your call.

Did you try the other two suggestions I provided? It is working for me.

**Comment by JamesHenry** [comment]
Thank you for submitting the issue, please see https://github.com/angular-eslint/angular-eslint/issues/86#issuecomment-661665652 for a brief personal update. I will endeavour to review this in the near future, if one of my co-contributors does not get to it first.

**Comment by guilhermetod** [comment]
This might work for you.

```
module.exports = {
  extends: [
    "plugin:@angular-eslint/recommended",
  ],
  plugins: ["@typescript-eslint", "@angular-eslint"],
  overrides: [
    {
      files: ["*.ts"],
      extends: [
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:@angular-eslint/recommended",
      ],
      parser: "@typescript-eslint/parser",
      parserOptions: {
        ecmaVersion: 2020,
        project: [
          "tsconfig.!(base).json", // Assuming you're using Angular 10 default folder structure.
          "e2e/tsconfig.json"
        ],
        sourceType: "module",
      },
    }
  ]
};

```

**Comment by alechemy** [comment]
@guilhermetod -- Thanks for that suggestion. I'd been experiencing the exact same problem in my project and your fix worked for me. I wound up tweaking it a bit, to be more explicit about which filetypes were extending which configs:

``` javascript
module.exports = {
  root: true,
  plugins: [
    "@typescript-eslint",
    "@angular-eslint"
  ],
  overrides: [
    {
      files: ["*.ts"],
      extends: [
        "plugin:@typescript-eslint/recommended",
        "plugin:@typescript-eslint/recommended-requiring-type-checking",
        "plugin:@angular-eslint/recommended",
      ],
      parser: "@typescript-eslint/parser",
      parserOptions: {
        ecmaVersion: 2020,
        project: [
          "tsconfig.app.json",
          "tsconfig.spec.json",
          "e2e/tsconfig.json"
        ],
        sourceType: "module",
      },
      rules: {
        // Additional rules for *.ts files
      }
    },
    {
      files: ["*.component.html"],
      extends: ["plugin:@angular-eslint/recommended"],
      rules: {
        // Additional rules for *.component.html files
      }
    }
  ]
};
```

**Comment by JamesHenry** [comment]
Thanks to all who have contributed to this issue!

Please could you try out the latest version I just published `v0.1.0-beta.1`

There should no longer be any requirement to manually set the `project` values if you are just using the `recommended` configuration from this package.

The refactored `builder` implementation in `v0.1.0-beta.1` is able to automatically take the `tsConfig` setting from the `angular.json` and apply it as the value for the `parserOptions.project` setting for the ESLint instance.

Cheers!

**Comment by delasteve** [comment]
@JamesHenry Thanks for taking a look at this. I think there may be a misunderstanding on the original problem. That's probably my fault for not being clear enough. 

It was never necessary to set `parserOptions.project` when using the `recommended` configuration. However, if you wanted to use type-checking (ie: extend from `"plugin:@typescript-eslint/recommended-requiring-type-checking"`) you were getting errors asking to set the `parserOptions.project`. I'm still getting those errors using just

```js
module.exports = {
  extends: [
    // comment this next line out to see no errors occur
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:@angular-eslint/recommended",
  ],
  plugins: ["@typescript-eslint", "@angular-eslint"],
};
```

I updated my sample project to Angular 10 and the `angular-eslint` version to `0.1.0-beta.1`. You can find that here: https://github.com/delasteve/eslint-angular-issue-sample-repo

I'm not familiar enough with the `@typescript-eslint` library, but would a possible solution be to add an option to `angular.json` such as `"enableTypechecking": true` that this builder would then read that option and have a `parserServices` to always be generated? I'm sure there's a more elegant way, but this would leave it up to the end user to determine if they want type-checking enabled or not.

**Comment by gagle** [comment]
I updated to the latest version 0.2.0-beta.1 and now I get this error:

```
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(tsConfig).
```

**Comment by JamesHenry** [comment]
@gagle yep it’s a breaking change version, the tsconfig property does not exist any more, please take a look at the integration-tests in this repo for how things are now configured as of v0.2

**Comment by gagle** [comment]
For the ones that are redirected by Google to this issue due to the error about the html file:

```
Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: src\app\app.component.html.
The extension for the file (.html) is non-standard. You should add "parserOptions.extraFileExtensions" to your config
```

With the latest version at the time of writing (0.2.0-beta.1), this problem dissapear with the following data structure:

```
"lint": {
  "builder": "@angular-eslint/builder:lint",
  "options": {
    "eslintConfig": ".eslintrc.json",
    "fix": true,
    "cache": true,
    "lintFilePatterns": ["src/**/*.ts"],
    "exclude": [
      "**/node_modules/**"
    ]
  }
}
```

The `lintFilePatterns` property is key here, just pass a glob with only the .ts files.

I have uploaded a repository with my favorite eslint configuration for Angular if you want to take a look: https://github.com/gagle/angular-starter

**Comment by alechemy** [comment]
@gagle Isn't the consequence of that change that only typescript files are linted? In other words, the desired outcome here is that template files (`*.component.html`) are linted successfully, not ignored entirely.

**Comment by gagle** [comment]
I will take a look linting html. First I wanted to ng lint successfully with a set of plugins.

**Comment by delasteve** [comment]
@gagle, @alechemy's [solution](https://github.com/angular-eslint/angular-eslint/issues/89#issuecomment-668279745) works for linting both TypeScript and HTML files. The only thing that will need to change with `0.2.0-beta.1` is the `parsersOptions.project` property.

OLD:

```js
project: [
  "tsconfig.app.json",
  "tsconfig.spec.json",
  "e2e/tsconfig.json"
],
```

NEW:

```js
project: [
  "tsconfig.eslint.json",
],
```

**Comment by JamesHenry** [comment]
@alechemy is correct - I wouldn't really describe this (https://github.com/angular-eslint/angular-eslint/issues/89#issuecomment-682582008) as a solution, you are simply no longer including external templates in your linting configuration.

ESLint naturally was not originally designed to lint HTML files (and it is not a use-case directly maintained by the core team per se), but we are able to leverage its flexibility in order to do so.

The key seems to be in how we can leverage `overrides` in our configs to ensure that one set of file extensions gets one set of parser/plugins/rules etc and another gets totally different ones.

The external template files (i.e. .html files) need to use the parser that this project provides, not `@typescript-eslint/parser`. If you look at the implementation details of the `@angular-eslint/recommended` config you will see how we leverage overrides to achieve this in the OOTB solution.

For custom solutions you can read up more about overrides here: https://eslint.org/docs/user-guide/configuring

**Comment by JamesHenry** [comment]
As a general note, I'm genuinely sorry about the churn in the configuration that has gone on. It's the reason for sticking to pre-stable version numbers for now while we figured things out.

People picking it up from scratch today should find things are a lot more straightforward and performant now - it's really people who already were using this project from previous versions that have to figure out all these fiddly bits of migration and I'm sorry about that! ❤️

**Comment by delasteve** [comment]
@JamesHenry, it comes with the territory when beta testing. 

Thanks for all your hard work.
